title: Trace Mayer
description: A core purpose of Trace Mayer is to be a champion of monetary sovereignty.
baseurl: "/trace-mayer" # Use the repository name
url: "https://www.trace-mayer.com" # Full URL to your project site
